#!/usr/bin/env bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       file name, like instead of executing this:
#
#           $ ./gradlew build
#
#       try to run this:
#
#           $ bash ./gradlew build
#
#   (2) The slickness of a shell script is an illusion and mistakes happen regularly.
#       If you add features to this script, ask yourself if you really
#       want to maintain them and doubt yourself when you think you
#       want to add "-e" to the $@ line (use \"set -e\" and trap exit
#       instead).
#
#       On MacOS in particular, base case variations of grep will silently decline
#       to simply cut characters.
#
##############################################################################

if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
    echo "Gradle 8.0"
    exit 0
fi

set -e

APP_NAME="Gradle"
APP_PATH=`dirname "$0"`
GRADLE_WRAPPER_DIR=`cd "$APP_PATH" && pwd`

export GRADLE_USER_HOME=$(pwd)/.gradle

JAVA_EXE=`which java`

if [ ! -x "$JAVA_EXE" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVA_EXE" >&2
    exit 1
fi

if ! command -v java &> /dev/null
then
    echo ""
    echo "  WARNING: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo ""
    echo "  Please set the JAVA_HOME variable in your environment to match the"
    echo "  location of your Java installation."
    echo ""
    exit 1
fi

exec "$JAVA_EXE" -Dorg.gradle.appname=$APP_BASE_NAME $DEFAULT_JVM_OPTS $JAVA_OPTS -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
