package com.example.ae2uel;

/**
 * ============================================================
 * AE2 UEL Addon - Version Tags
 * ============================================================
 * Auto-generated by Gradle during build
 * DO NOT EDIT MANUALLY
 */
public class Tags {
    public static final String MODID = "@MODID@";
    public static final String MODNAME = "@MODNAME@";
    public static final String VERSION = "@VERSION@";

    public static final String MC_VERSION = "1.12.2";
    public static final String AE2_UEL_VERSION = "rv6-stable-7";
}
